### ISSUE TITLE
GATT Characteristics not recognized

### ISSUE THREAD

**Issue by beegee-tokyo** [NordicSemiconductor/Android-nRF-Connect#52]
I am using GATT characteristics from [Bluetooth Specifications](https://www.bluetooth.com/specifications/gatt/characteristics), specifically 0x2A17 (Temperature Celsius), 0x2A6F (Humidity), 0x2A3D (String) and 0x2A46 (New Alert) on my BLE device.
All GATT characteristics are shown in nRF Connect, but shown as "Unknown Characteristic" and "Unknown Descriptor".
I hoped there is support for standard GATT characteristics in the application. Or maybe I am doing something wrong in the definition of the characteristics and descriptors.
Any advice?

**Comment by philips77** [comment]
So... 0x2A17 is Time Update State (Guess you meant 0x2A1F), Humidity should work, 2A3D I'm adding right now (among others), and New Alert also should work. Could you paste here the screenshot from the app?
There is support for those listed in menu->Definitions.

**Comment by philips77** [comment]
I've just released version 4.17.0 which should support all mentioned characteristics. Could you verify when you get the update?

**Comment by beegee-tokyo** [comment]
Updated to the latest version, still the same. I have to admit that I am not testing a nRF chip, but the BLE of an ESP32 module.
I guess the problem is within my device and my descriptors. Have to learn how to correctly setup the characteristics and descriptors.
Here a screenshot of the app together with the debug messages.

![screenshot_2017-12-21-10-05-59 1](https://user-images.githubusercontent.com/512690/34237339-1ab6f30c-e637-11e7-8f9d-20b8024faf70.png)

**Comment by philips77** [comment]
You have to set those uuids to characteristics, not descriptors. Those characteristics don't need descriptors unless they are notifying or indicating, then the CCC descriptor is required in such char. Right now your characteristic have 128bit random uuids.

**Comment by beegee-tokyo** [comment]
Thank you very much. I am still learning about BLE stuff. Now my ESP32 sends correct data within correct characteristics.

Your tool is really very good to learn and debug BLE apps!

Merry Christmas and a Happy New Year!

![screenshot_2017-12-21-18-04-42](https://user-images.githubusercontent.com/512690/34250998-8e8e19e4-e679-11e7-8d8a-cdb62a7e5f6a.png)
